server:
  port: 5200
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/op_log?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true

log:
  replace:
    packageName: com.jianghao.oplog.orm.po
    updateInfoTemplate: {}:{}->{}
    insertInfoTemplate: {}:{}
    deleteInfoTemplate: {}:{}