server:
  port: 8080
  servlet:
    context-path: /quartz
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      druid:
        max-active: 100
        initial-size: 10
        max-wait: 10000
        filters: wall,stat
        wall:
          multi-statement-allow: true
      primary: oneNetcom
      datasource:
        oneNetcom:
          driver-class-name: com.mysql.cj.jdbc.Driver
          password: 123456
          url: jdbc:mysql://localhost:3306/scaffolder-project?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
          username: root
          type: com.alibaba.druid.pool.DruidDataSource
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
            instanceName: clusteredScheduler #quartzScheduler
            jobStore:
              acquireTriggersWithinLock: true   #在锁定状态下获取触发器
              class: org.quartz.impl.jdbcjobstore.JobStoreTX #持久化配置
              driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #我们仅为数据库制作了特定于数据库的代理
              useProperties: true #以指示JDBCJobStore将JobDataMaps中的所有值都作为字符串，因此可以作为名称 - 值对存储而不是在BLOB列中以其序列化形式存储更多复杂的对象。从长远来看，这是更安全的，因为您避免了将非String类序列化为BLOB的类版本问题。
              tablePrefix: qrtz_  #数据库表前缀
              misfireThreshold: 6000 #在被认为“失火”之前，调度程序将“容忍”一个Triggers将其下一个启动时间通过的毫秒数。默认值（如果您在配置中未输入此属性）为60000（60秒）。
              clusterCheckinInterval: 5000 #设置此实例“检入”*与群集的其他实例的频率（以毫秒为单位）。影响检测失败实例的速度。
              isClustered: false #打开群集功能,集群模式需要在多台服务器上做时间同步或者使用zookeeper去解决
            threadPool: #连接池
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10 #最大线程个数
              threadPriority: 5 #线程优先级
              threadsInheritContextClassLoaderOfInitializingThread: true
        startup-delay: 30
  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false
    cache-period: 0
    mode: LEGACYHTML5
    template:
      cache: false

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml  #配置mapper xml文件所在路径
  type-aliases-package: com.jianghao.quartz.orm.po  #配置映射类所在包名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace
